In [3]:
import os
import pandas as pd
path= '/Users/bokie/code/python/CMS/可转债套利/cms/stat_arb/pair_perform'
files = os.listdir(path)
dfs = []
for file in files:
    if file == '300763.SZ@300724.SZ.xlsx':
        continue
    tmp_df = pd.read_excel(f'{path}/{file}')
    dfs.append(tmp_df)
df_peform_total = pd.concat(dfs,axis=0)    
pd.set_option('display.float_format', lambda x: '%.3f' % x)
df_peform_total.sort_values(by='net profit',ascending=False).iloc[:,1:].to_excel('pair_perform.xlsx',index=False)
df_peform_total.sort_values(by='net profit',ascending=False).iloc[:,1:]

,pair,value,net profit,total rtn rate,total rtn,sharpe,max drawdown,longest drawdown
0,002013.SZ@600372.SH,5181372.0@15797760.0,3002195.839,0.579,0.579,4.222,0.067,81
0,000789.SZ@002233.SZ,5343780.0@11537325.0,2278579.705,0.428,0.428,4.238,0.046,35
0,688388.SH@600110.SH,530145.0@5456781.0,1525900.491,2.857,2.857,12.766,0.065,50
0,300760.SZ@603259.SH,19587300.0@2080250.0,391794.750,0.188,0.188,0.958,0.121,116
0,002555.SZ@002624.SZ,4057319.0@585648.0,326480.868,0.557,0.557,3.122,0.118,130
0,000088.SZ@600798.SH,127506.0@1770720.0,251996.169,1.960,1.960,8.304,0.093,33
0,600163.SH@600021.SH,2561416.0@519024.0,203630.395,0.392,0.392,1.623,0.172,161
0,300750.SZ@300014.SZ,8313390.0@681000.0,169066.079,0.248,0.248,1.163,0.152,150
0,002236.SZ@002415.SZ,636120.0@2013238.0,158912.148,0.250,0.250,1.481,0.094,156
0,600531.SH@000426.SZ,586988.0@198462.0,127681.278,0.643,0.643,3.647,0.090,44
0,601186.SH@601390.SH,107965.0@493805.0,48131.154,0.446,0.446,6.459,0.031,62
0,600316.SH@000738.SZ,332175.0@53082.0,8035.209,0.151,0.151,0.785,0.167,288
0,000402.SZ@600466.SH,287532.0@7564.0,6869.006,0.911,0.911,4.732,0.100,130