# single performance stat

In [7]:
import os
import pandas as pd


# pair_name = '123046.SZ@300587.SZ.csv'
# pair_name = '113642.SH@603185.SH.csv'
# pair_name = '110061.SH@600674.SH.csv'
# pair_name = '128081.SZ@002203.SZ.csv'
# pair_name = '113016.SH@601127.SH.csv'
# pair_name = '128017.SZ@002597.SZ.csv'
# pair_name = '113537.SH@603348.SH.csv'
# pair_name = '123027.SZ@300487.SZ.csv'
pair_name = '113534.SH@603876.SH.csv'
# pair_name = '113025.SH@601677.SH.csv'
# pair_name = '123031.SZ@300655.SZ.csv'
# pair_name = '128029.SZ@002078.SZ.csv'

In [8]:

folders = os.listdir('./daily_track')
print('track days: ',len(folders)-1)
history_performance = []
for folder in folders:
    if folder == '.DS_Store':
        continue
    # print(os.listdir(f'./daily_track/{folder}'))

    if pair_name not in os.listdir(f'./daily_track/{folder}'):
        continue

    df_tmp = pd.read_csv(f'./daily_track/{folder}/{pair_name}')
    if len(df_tmp) == 3:
        history_performance.append(df_tmp)
print('open by signal times: ',len(history_performance))

track days:  13
open by signal times:  8

In [9]:
assert len(history_performance)!=0

In [10]:
# if len(history_performance)!= 0:
df_perform = pd.concat(history_performance,axis=0)
cols = df_perform.columns.to_list()
cols = ['date'] + cols[1:]
df_perform.columns = cols
df_perform.loc[2].sort_values(by='date')

,date,pair,cash,signal,bond price,stock price,bond hold,stock hold,commission,tax,reverse open,diff,asset value,net value,open/close
2,2022-09-14 14:13:00,113534.SH@603876.SH,6.904670,0.0,401.410,56.58,0.0,0.0,0.160424,0.400711,False,0.001656,0.0,6.904670,"0.019,0.002"
2,2022-09-15 15:00:00,113534.SH@603876.SH,-2.296995,00,374.984,54.43,0.0,0.0,0.152109,0.000000,False,-0.026164,0.0,-2.296995,"0.019,0.002"
2,2022-09-19 15:00:00,113534.SH@603876.SH,1.657935,00,357.814,51.63,0.0,0.0,0.144089,0.000000,False,-0.013314,0.0,1.657935,"0.019,0.002"
2,2022-09-20 13:30:00,113534.SH@603876.SH,5.645883,00,381.197,55.08,0.0,0.0,0.152584,0.000000,False,-0.001472,0.0,5.645883,"0.019,0.002"
2,2022-09-22 15:00:00,113534.SH@603876.SH,3.310221,0.0,391.431,55.61,0.0,0.0,0.155887,0.388002,False,0.008854,0.0,3.310221,"0.019,0.002"
2,2022-09-23 13:51:00,113534.SH@603876.SH,6.072424,00,382.434,54.44,0.0,0.0,0.153126,0.000000,False,-0.001946,0.0,6.072424,"0.019,0.002"
2,2022-09-26 15:00:00,113534.SH@603876.SH,-2.637018,00,399.073,57.63,0.0,0.0,0.161477,0.000000,False,-0.024013,0.0,-2.637018,"0.019,0.002"
2,2022-09-28 15:00:00,113534.SH@603876.SH,-5.222603,0.0,399.664,56.00,0.0,0.0,0.157377,0.387222,False,0.030404,0.0,-5.222603,"0.019,0.002"

In [11]:
df_perform.loc[2]['net value'].sum()

13.434515719741526

# total performance stat

In [12]:
df_stat = pd.DataFrame(columns=['total pnl','open times','track days'])
names = ['123046.SZ@300587.SZ.csv',
'113642.SH@603185.SH.csv',
'110061.SH@600674.SH.csv',
'128081.SZ@002203.SZ.csv',
'113016.SH@601127.SH.csv',
'128017.SZ@002597.SZ.csv',
'113537.SH@603348.SH.csv',
'123027.SZ@300487.SZ.csv',
'113534.SH@603876.SH.csv',
'113025.SH@601677.SH.csv',
'123031.SZ@300655.SZ.csv',
'128029.SZ@002078.SZ.csv']
for name in names:
    folders = os.listdir('./daily_track')
    # print('track days: ',len(folders)-1)
    history_performance = []
    track_days = 0
    for folder in folders:
        if folder == '.DS_Store':
            continue
        # print(os.listdir(f'./daily_track/{folder}'))

        if name not in os.listdir(f'./daily_track/{folder}'):
            continue
        track_days += 1
        df_tmp = pd.read_csv(f'./daily_track/{folder}/{name}')
        if len(df_tmp) == 3:
            history_performance.append(df_tmp)
    # print('open by signal times: ',len(history_performance))
    opentimes = len(history_performance)
    if opentimes!=0:
        df_perform = pd.concat(history_performance,axis=0)
        cols = df_perform.columns.to_list()
        cols = ['date'] + cols[1:]
        df_perform.columns = cols
        df_perform.loc[2].sort_values(by='date')
        total_pnl = df_perform.loc[2]['net value'].sum()
        line = [total_pnl,opentimes]
        df_stat.loc[name,'total pnl'] = total_pnl
        df_stat.loc[name,'open times'] = opentimes
        df_stat.loc[name,'track days'] = track_days
    else:
        df_stat.loc[name,'total pnl'] = 0
        df_stat.loc[name,'open times'] = 0
        df_stat.loc[name,'track days'] = track_days
# df_stat['track days'] = [len(folders)-1]*len(df_stat)
df_stat

                         total pnl open times track days
123046.SZ@300587.SZ.csv  -0.013472         11         13
113642.SH@603185.SH.csv  -0.783951          4         13
110061.SH@600674.SH.csv   0.322309          5         13
128081.SZ@002203.SZ.csv  -0.988591          5         13
113016.SH@601127.SH.csv   2.407669          8         13
128017.SZ@002597.SZ.csv   7.847451         12         13
113537.SH@603348.SH.csv          0          0         13
123027.SZ@300487.SZ.csv          0          0         13
113534.SH@603876.SH.csv  13.434516          8         13
113025.SH@601677.SH.csv   7.358862          9         13
123031.SZ@300655.SZ.csv -10.583835          7         13
128029.SZ@002078.SZ.csv   2.447083          2          4